{
 "title": "Production Incident Lab",
 "tags": [
  "production",
  "incident",
  "postgres",
  "fastapi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "5xx Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{route=\"/orders\",status=~\"5..\"}[1m])) / clamp_min(sum(rate(http_requests_total{route=\"/orders\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "HTTP p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{route=\"/orders\",method=\"POST\"}[1m])))",
     "legendFormat": "p95 ms"
    }
   ]
  },
  {
   "title": "DB pool usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "db_pool_checked_out", "legendFormat": "checked out" },
    { "expr": "db_pool_size", "legendFormat": "pool size" }
   ]
  },
  {
   "title": "DB acquire p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.95, sum by (le) (rate(db_connection_acquire_seconds_bucket[1m])))",
     "legendFormat": "p95 ms"
    }
   ]
  },
  {
   "title": "DB connection hold p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.95, sum by (le) (rate(db_connection_hold_seconds_bucket[1m])))",
     "legendFormat": "p95 ms"
    }
   ]
  },
  {
   "title": "Downstream p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.95, sum by (le) (rate(downstream_request_duration_seconds_bucket[1m])))",
     "legendFormat": "p95 ms"
    }
   ]
  },
  {
   "title": "DB pool timeouts / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_pool_timeout_total[1m])",
     "legendFormat": "timeouts/s"
    }
   ]
  }
 ]
}